[package]
name = "churust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "Churust — a Ktor-inspired, secure, easy-to-learn Rust web framework (Churro + Rust)."

[package.metadata.docs.rs]
all-features = true

[dependencies]
churust-core = { workspace = true }
churust-macros = { workspace = true }
http = { workspace = true }
tokio = { workspace = true }
churust-json = { workspace = true, optional = true }
churust-logging = { workspace = true, optional = true }
churust-cors = { workspace = true, optional = true }
churust-auth = { workspace = true, optional = true }

[features]
default = []
json = ["dep:churust-json"]
logging = ["dep:churust-logging"]
cors = ["dep:churust-cors"]
auth = ["dep:churust-auth"]
tls = ["churust-core/tls"]
ws = ["churust-core/ws"]
fs = ["churust-core/fs"]
multipart = ["churust-core/multipart"]
full = ["json", "logging", "cors", "auth"]
