[package]
name = "churust"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../README.md"
description = "Churust — a Ktor-inspired, secure, easy-to-learn Rust web framework (Churro + Rust)."

[dependencies]
churust-core = { path = "../churust-core", version = "0.1.0" }
churust-macros = { path = "../churust-macros", version = "0.1.0" }
http = { workspace = true }
tokio = { workspace = true }
churust-json = { path = "../churust-json", version = "0.1.0", optional = true }
churust-logging = { path = "../churust-logging", version = "0.1.0", optional = true }
churust-cors = { path = "../churust-cors", version = "0.1.0", optional = true }
churust-auth = { path = "../churust-auth", version = "0.1.0", optional = true }

[features]
default = []
json = ["dep:churust-json"]
logging = ["dep:churust-logging"]
cors = ["dep:churust-cors"]
auth = ["dep:churust-auth"]
tls = ["churust-core/tls"]
ws = ["churust-core/ws"]
full = ["json", "logging", "cors", "auth"]
